package generateroutesfile

import (
	"bufio"
	"fmt"
	"os"
	"time"

	"github.com/net12labs/cirm/dali/work/task"
)

type GenerateRoutesFile struct {
	Task task.Task
}

func (rf *GenerateRoutesFile) generateBirdConfig(outputFile, gateway string, compact bool) (int, error) {
	totalRoutes := 0
	// for _, routes := range rf.routes {
	// 	totalRoutes += len(routes)
	// }

	f, err := os.Create(outputFile)
	if err != nil {
		return 0, err
	}
	defer f.Close()

	w := bufio.NewWriter(f)
	defer w.Flush()

	fmt.Fprintln(w, "# BIRD Generated Configuration")
	fmt.Fprintln(w, "# Generated by fetch_routes.go")
	fmt.Fprintf(w, "# Date: %s\n", time.Now().UTC().Format("2006-01-02 15:04:05 UTC"))
	fmt.Fprintf(w, "# Total Routes: %d\n", totalRoutes)

	if !compact {
		fmt.Fprintln(w)
	}

	fmt.Fprintln(w, "protocol static {")
	fmt.Fprintln(w, "    ipv6;")

	// Sort ASNs for consistent output
	// var asns []int
	// for asn := range rf.routes {
	// 	asns = append(asns, asn)
	// }
	// sort.Ints(asns)

	// for _, asn := range asns {
	// 	routes := rf.routes[asn]
	// 	if len(routes) == 0 {
	// 		continue
	// 	}

	// 	fmt.Fprintf(w, "    # Configuration for ASN AS%d\n", asn)
	// 	for _, route := range routes {
	// 		fmt.Fprintf(w, "    route %s via %s;\n", route, gateway)
	// 	}

	// 	if !compact {
	// 		fmt.Fprintln(w)
	// 	}
	// }

	fmt.Fprintln(w, "}")

	return totalRoutes, nil
}
